[package]
name = "dns-proxy"
version = "0.1.0"
authors = ["rbmj <rbmj@verizon.net>"]

[dependencies]
dns-parser = "0.6.0"
lru-cache = "0.1.0"
rand = "0.3.15"
byteorder = "1"
itertools = "0.5"
quick-error = "1.0.0"
